import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { cleanLocalExcludeContent, installHarness, isHarnessInstalled, uninstallHarness } from "../src/main/teamwork-harness.js";
import { makeTempRoot, writeJson, writeText } from "./helpers.js";

const execFileAsync = promisify(execFile);

const harnessOptions = {
  githubLogin: "SharkUI",
  githubUserId: 3960864,
  machineId: "abcdef",
  agent: "codex",
  repo: "SharkUI/AIBF",
};

describe("teamwork harness install", () => {
  it("writes local harness files and ignored root adapters", async () => {
    const root = await makeTempRoot("teamwork-harness");
    const repo = await createRealGitRepoFixture(root);

    await installHarness(repo, harnessOptions);

    await expect(isHarnessInstalled(repo)).resolves.toBe(true);
    await expect(fs.readFile(path.join(repo, "AGENTS.md"), "utf8")).resolves.toContain("sharkbay-generated: true");
    await expect(fs.readFile(path.join(repo, "AGENTS.md"), "utf8")).resolves.toContain("Follow this workflow for every task that edits project files");
    await expect(fs.readFile(path.join(repo, "CLAUDE.md"), "utf8")).resolves.toContain("sharkbay-generated: true");
    await expect(fs.readFile(path.join(repo, "GEMINI.md"), "utf8")).resolves.toContain("sharkbay-generated: true");
    await expect(fs.readFile(path.join(repo, "QWEN.md"), "utf8")).resolves.toContain("sharkbay-generated: true");
    await expect(fs.readFile(path.join(repo, ".kiro", "steering", "sharkbay-protocol.md"), "utf8")).resolves.toContain("sharkbay-generated: true");
    await expect(fs.stat(path.join(repo, ".sharkbay", "harness", "instructions")).catch(() => null)).resolves.toBeNull();
    const protocol = await fs.readFile(path.join(repo, ".sharkbay", "harness", "protocol.md"), "utf8");
    expect(protocol).toContain("Repo: SharkUI/AIBF");
    expect(protocol).not.toContain("- Agent:");
    expect(protocol).toContain("agent: # e.g. Codex GPT-5.5");
    expect(protocol).toContain("Use the actual task executor identity in `agent`");
    const exclude = await fs.readFile(path.join(repo, ".git", "info", "exclude"), "utf8");
    expect(exclude).toContain("/AGENTS.md");
    expect(exclude).toContain("/CLAUDE.md");
    expect(exclude).toContain("/GEMINI.md");
    expect(exclude).toContain("/QWEN.md");
    expect(exclude).toContain("/.kiro/steering/sharkbay-protocol.md");
  });

  it("refuses to overwrite an existing user root instruction file", async () => {
    const root = await makeTempRoot("teamwork-harness-conflict");
    const repo = await createRealGitRepoFixture(root);
    const agentsPath = path.join(repo, "AGENTS.md");
    await writeText(agentsPath, "# Existing agent rules\n");

    await expect(installHarness(repo, harnessOptions)).rejects.toThrow(/AGENTS\.md/);
    await expect(fs.readFile(agentsPath, "utf8")).resolves.toBe("# Existing agent rules\n");
    await expect(isHarnessInstalled(repo)).resolves.toBe(false);
  });

  it("refuses to install into a directory that is not a git worktree", async () => {
    const root = await makeTempRoot("teamwork-harness-no-git");
    const repo = path.join(root, "plain-folder");
    await fs.mkdir(repo, { recursive: true });

    await expect(installHarness(repo, harnessOptions)).rejects.toThrow(/requires a Git repository/);
    await expect(fs.stat(path.join(repo, ".git")).catch(() => null)).resolves.toBeNull();
    await expect(isHarnessInstalled(repo)).resolves.toBe(false);
  });

  it("updates root adapters that were generated by SharkBay", async () => {
    const root = await makeTempRoot("teamwork-harness-generated");
    const repo = await createRealGitRepoFixture(root);
    const agentsPath = path.join(repo, "AGENTS.md");
    await writeText(agentsPath, "<!-- sharkbay-generated: true -->\nold adapter\n");

    await installHarness(repo, harnessOptions);

    const content = await fs.readFile(agentsPath, "utf8");
    expect(content).toContain("This worktree uses SharkBay Teamwork.");
    expect(content).not.toContain("old adapter");
  });

  it("overwrites SharkBay-generated agent adapters with updated content", async () => {
    const root = await makeTempRoot("teamwork-harness-legacy");
    const repo = await createRealGitRepoFixture(root);
    await writeText(path.join(repo, "CLAUDE.md"), "<!-- sharkbay-generated: true -->\nold claude adapter\n");
    await writeText(path.join(repo, "GEMINI.md"), "<!-- sharkbay-generated: true -->\nold gemini adapter\n");
    await writeText(path.join(repo, ".sharkbay", "harness", "instructions", "claude.md"), "old claude instruction\n");
    await writeText(path.join(repo, ".sharkbay", "harness", "instructions", "gemini.md"), "old gemini instruction\n");
    await writeText(path.join(repo, ".git", "info", "exclude"), ["/.sharkbay/", "/AGENTS.md", "/CLAUDE.md", "/GEMINI.md", ""].join("\n"));

    await installHarness(repo, harnessOptions);

    const claude = await fs.readFile(path.join(repo, "CLAUDE.md"), "utf8");
    expect(claude).toContain("This worktree uses SharkBay Teamwork.");
    expect(claude).not.toContain("old claude adapter");
    const gemini = await fs.readFile(path.join(repo, "GEMINI.md"), "utf8");
    expect(gemini).toContain("This worktree uses SharkBay Teamwork.");
    expect(gemini).not.toContain("old gemini adapter");
    await expect(fs.stat(path.join(repo, ".sharkbay", "harness", "instructions")).catch(() => null)).resolves.toBeNull();
    const exclude = await fs.readFile(path.join(repo, ".git", "info", "exclude"), "utf8");
    expect(exclude).toContain("/AGENTS.md");
    expect(exclude).toContain("/CLAUDE.md");
    expect(exclude).toContain("/GEMINI.md");
    expect(exclude).toContain("/QWEN.md");
  });

  it("refuses to overwrite user-owned adapter files", async () => {
    const root = await makeTempRoot("teamwork-harness-user-legacy");
    const repo = await createRealGitRepoFixture(root);
    await writeText(path.join(repo, "CLAUDE.md"), "# User Claude rules\n");

    await expect(installHarness(repo, harnessOptions)).rejects.toThrow(/CLAUDE\.md/);
    await expect(fs.readFile(path.join(repo, "CLAUDE.md"), "utf8")).resolves.toBe("# User Claude rules\n");
  });

  it("uninstalls local teamwork files and removes only SharkBay exclude entries", async () => {
    const root = await makeTempRoot("teamwork-harness-uninstall");
    const repo = await createRealGitRepoFixture(root);
    await writeText(path.join(repo, ".git", "info", "exclude"), ["node_modules/", "dist/", ""].join("\n"));

    await installHarness(repo, harnessOptions);
    const result = await uninstallHarness(repo);

    expect(result.removedPaths).toContain(".sharkbay");
    expect(result.removedPaths).toContain("AGENTS.md");
    expect(result.removedPaths).toContain("CLAUDE.md");
    expect(result.removedPaths).toContain("GEMINI.md");
    expect(result.removedPaths).toContain("QWEN.md");
    expect(result.removedPaths).toContain(".kiro/steering/sharkbay-protocol.md");
    expect(result.excludeRemovedLines).toEqual(["/.sharkbay/", "/AGENTS.md", "/CLAUDE.md", "/GEMINI.md", "/QWEN.md", "/.kiro/steering/sharkbay-protocol.md"]);
    await expect(isHarnessInstalled(repo)).resolves.toBe(false);
    await expect(fs.stat(path.join(repo, ".sharkbay")).catch(() => null)).resolves.toBeNull();
    await expect(fs.stat(path.join(repo, "AGENTS.md")).catch(() => null)).resolves.toBeNull();
    await expect(fs.stat(path.join(repo, "CLAUDE.md")).catch(() => null)).resolves.toBeNull();
    await expect(fs.stat(path.join(repo, "GEMINI.md")).catch(() => null)).resolves.toBeNull();
    await expect(fs.stat(path.join(repo, "QWEN.md")).catch(() => null)).resolves.toBeNull();
    await expect(fs.stat(path.join(repo, ".kiro", "steering", "sharkbay-protocol.md")).catch(() => null)).resolves.toBeNull();
    await expect(fs.readFile(path.join(repo, ".git", "info", "exclude"), "utf8")).resolves.toBe("node_modules/\ndist/\n");
  });

  it("restores preexisting local exclude content exactly", async () => {
    const root = await makeTempRoot("teamwork-harness-uninstall-exclude-restore");
    const repo = await createRealGitRepoFixture(root);
    const originalExclude = ["node_modules/", "/.sharkbay/", "# user note", ""].join("\n");
    await writeText(path.join(repo, ".git", "info", "exclude"), originalExclude);

    await installHarness(repo, harnessOptions);
    await uninstallHarness(repo);

    await expect(fs.readFile(path.join(repo, ".git", "info", "exclude"), "utf8")).resolves.toBe(originalExclude);
  });

  it("preserves user-owned adapter files during uninstall", async () => {
    const root = await makeTempRoot("teamwork-harness-uninstall-user-file");
    const repo = await createRealGitRepoFixture(root);
    await writeText(path.join(repo, "AGENTS.md"), "# User agent rules\n");
    await fs.mkdir(path.join(repo, ".sharkbay", "harness"), { recursive: true });
    await writeText(path.join(repo, ".sharkbay", "harness", "protocol.md"), "# protocol\n");

    const result = await uninstallHarness(repo);

    expect(result.skippedPaths).toContain("AGENTS.md");
    await expect(fs.readFile(path.join(repo, "AGENTS.md"), "utf8")).resolves.toBe("# User agent rules\n");
    await expect(fs.stat(path.join(repo, ".sharkbay")).catch(() => null)).resolves.toBeNull();
  });

  it("cleans local exclude content without touching unrelated lines", () => {
    const cleaned = cleanLocalExcludeContent(["# local", "/.sharkbay/", "/AGENTS.md", "/CLAUDE.md", "/GEMINI.md", "/QWEN.md", "/.kiro/steering/sharkbay-protocol.md", ".env", ""].join("\n"));

    expect(cleaned.removedLines).toEqual(["/.sharkbay/", "/AGENTS.md", "/CLAUDE.md", "/GEMINI.md", "/QWEN.md", "/.kiro/steering/sharkbay-protocol.md"]);
    expect(cleaned.content).toBe("# local\n.env\n");
  });
});

async function createRealGitRepoFixture(root: string, name = "FixtureApp"): Promise<string> {
  const repo = path.join(root, name);
  await fs.mkdir(repo, { recursive: true });
  await writeJson(path.join(repo, "package.json"), { name: name.toLowerCase(), version: "1.0.0" });
  await execFileAsync("git", ["init"], { cwd: repo });
  return repo;
}
