export const ipcChannels = {
  listRoots: "config:listRoots",
  addRoot: "config:addRoot",
  removeRoot: "config:removeRoot",
  setAppearanceTheme: "config:setAppearanceTheme",
  scanProjects: "projects:scan",
  getProjectDetail: "projects:getDetail",
  listProjectFiles: "projects:listFiles",
  createTerminal: "terminal:create",
  terminalInput: "terminal:input",
  resizeTerminal: "terminal:resize",
  closeTerminal: "terminal:close",
  terminalData: "terminal:data",
  terminalUpdate: "terminal:update",
  terminalExit: "terminal:exit",
  createBrowser: "browser:create",
  browserNavigate: "browser:navigate",
  browserResize: "browser:resize",
  browserClose: "browser:close",
  browserGoBack: "browser:goBack",
  browserGoForward: "browser:goForward",
  browserReload: "browser:reload",
  browserUpdate: "browser:update",
  listAgentClis: "agents:listClis",
  agentStatus: "agents:status",
} as const;
